### ISSUE TITLE
Für jede Frage ein einzelnes Jupyter-Notebook erstellen.

### ISSUE THREAD

**Issue by crltfrnk** [crltfrnk/2022_BdK6.5.3-P5_Gruppe_2#2]
Am besten in einem Ordner, sonnst wird es vermutlich irgendwann zu unübersichtlich..  
Wie benennen wir die Notebooks?  

- [x] **"..._Frage_01"**   

oder gibt es andere Vorschläge?

**Comment by Telemichi** [comment]
Ich persönlich würde sprechende Namen besser finden, also bspw. Durschnittliche_Songlänge, sodass man direkt weiß welchen inhalt man erwarten kann. 
Außerdem muss man sich dann nicht merken welche Nummer zu welcher Frage gehört ^^'
